apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: kafka-manager
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: kafka-manager
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kafka-manager
    labels:
      app: kafka-manager
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kafka-manager
    template:
      metadata:
        labels:
          app: kafka-manager
      spec:
        containers:
        - env:
          - name: ZK_HOSTS
            value: zookeeper:2181
          - name: JAVA_OPTS
            value: -Xmx1024m
          image: docker.io/spicysomtam/kafka-manager:1.3.3.14
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          name: kafka-manager
          ports:
          - containerPort: 9000
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsUser: 1000060000
        terminationGracePeriodSeconds: 30
kind: List
metadata: {}
